= UE Boom Reverse Engineering

Taking an android app apk converted to a jar to learn about bluetooth command data format to send over bluetooth without the app.

The goal was to reverse engineer the spp (rfcomm) socket message format to disable bluetooth low energy, since the new app doesn't have that option anymore. Testing to see if disabling BLE to improve battery life (link:https://blog.countableset.com/2022/02/22/ue-boom-reverse-engineering/[blog post]).

== Reference

=== SPP

`com.logitech.ue.centurion.device.command.UEDeviceCommand.UECommand`::
    List of commands to be able to send
`com.logitech.ue.centurion.device.command.UEGenericDeviceCommand.buildCommandData`::
    Method that builds the bytes to send
`com.logitech.ue.centurion.device.UESPPDevice`::
    Methods that execute those commands

=== BLE Characteristics

`com.logitech.ue.centurion.ble.UEBLECharacteristics`::
    List of UUIDs for BLE characteristics

== Commands

Adjust Volume Up by One:: `04 01 BB 01 01`
Announce Battery Level:: `02 01 6B`
Set Sonfication (Conga):: `03 01 65 01`
Set Sonfication (None):: `03 01 65 00`
Emit Sound (Power On):: `04 01 6C 60 C0`
Set BLE State Off:: `03 01 B9 00`
Set BLE State On:: `03 01 B9 01`
